name: 'Deploy to AWS S3'
description: 'Deploy a static website using AWS S3'
inputs:
  bucket:
    description: 'The S3 Bucket name'
    required: true
  bucket-region:
    description: 'The S3 Bucket region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the file'
    required: true
runs:
  using: 'node20'
  main: 'main.js'